# -*- coding: utf-8 -*-
"""HMAC.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNkBB6Jeo0JysAMh10xkwDXr4-bBiW9J
"""

import hashlib
secret_key = "secret key".encode()
m = "Hello".encode()
sha256 = hashlib.sha256()
sha256.update(secret_key)
sha256.update(m)
hmac = sha256.digest()
print(m,hmac)
#bob receives and validates
sha256 = hashlib.sha256()
sha256.update(secret_key)
sha256.update(m)
hmac = sha256.digest()
print(m,hmac)